apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: demo-secret
  namespace: demo
spec:
  data:
  - remoteRef:
      key: demo/demo-app
      property: username
    secretKey: username
  - remoteRef:
      key: demo/demo-app
      property: password
    secretKey: password
  refreshInterval: 1h
  secretStoreRef:
    kind: SecretStore
    name: openbao
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    name: demo-secret

