apiVersion: v1
data:
  ca.crt: |-
    -----BEGIN CERTIFICATE-----
    MIIBmjCCAT+gAwIBAgIUDnKoaJPWNnlvqRa93YQ2AUVW9EEwCgYIKoZIzj0EAwIw
    GjEYMBYGA1UEAxMPSG9tZWxhYiBSb290IENBMB4XDTI2MDkxNzExMTMzOFoXDTM2
    MDkxNDExMTQwOFowGjEYMBYGA1UEAxMPSG9tZWxhYiBSb290IENBMFkwEwYHKoZI
    zj0CAQYIKoZIzj0DAQcDQgAE2nfvJZ6bHJrIWM0r/jvIEw0UiVWRDKLVfL11/8g/
    iHSP4rsuuR+qazVSFxxYKFtZ+oC4XVtL+102pWLx7Ww1x6NjMGEwDgYDVR0PAQH/
    BAQDAgEGMA8GA1UdEwEB/wQFMAMBAf8wHQYDVR0OBBYEFGg+olpG00GvKOmG9pap
    DTSZXk+HMB8GA1UdIwQYMBaAFGg+olpG00GvKOmG9papDTSZXk+HMAoGCCqGSM49
    BAMCA0kAMEYCIQCAUcbUgDDHSJqXkbFN3fIa9t53++XCIeSXME0O8XQOQwIhAM9K
    Y3WP3AnWLmvK9U5q3ShguztXv6AqUjZol0jE7rvv
    -----END CERTIFICATE-----
kind: ConfigMap
metadata:
  name: homelab-root-ca
  namespace: demo
