path "sys/health"                { capabilities = ["read", "sudo"] }
path "sys/capabilities-self"     { capabilities = ["update"] }
path "sys/mounts"                { capabilities = ["read", "list"] }
path "sys/mounts/*"              { capabilities = ["create", "read", "update", "delete", "list", "sudo"] }
path "sys/auth"                  { capabilities = ["read", "list"] }
path "sys/auth/*"                { capabilities = ["create", "read", "update", "delete", "sudo"] }
path "sys/policies/acl"          { capabilities = ["list"] }
path "sys/policies/acl/*"        { capabilities = ["create", "read", "update", "delete", "list"] }
path "sys/audit"                 { capabilities = ["read", "list", "sudo"] }
path "sys/audit/*"               { capabilities = ["create", "read", "update", "delete", "sudo"] }
path "sys/leases/*"              { capabilities = ["create", "read", "update", "delete", "list", "sudo"] }
path "sys/storage/raft/snapshot" { capabilities = ["read"] }
path "sys/generate-root-token/attempt" { capabilities = ["create", "read", "update", "delete", "sudo"] }
path "sys/generate-root-token/update"  { capabilities = ["create", "update", "sudo"] }
path "sys/decode-token"                { capabilities = ["create", "update"] }
path "auth/*"                    { capabilities = ["create", "read", "update", "delete", "list", "sudo"] }
path "identity/*"                { capabilities = ["create", "read", "update", "delete", "list"] }
path "secret/*"                  { capabilities = ["create", "read", "update", "delete", "list"] }
path "database/*"                { capabilities = ["create", "read", "update", "delete", "list"] }
