apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: miniflux-db
  namespace: demo
spec:
  refreshInterval: 30m

  target:
    name: miniflux-db
    creationPolicy: Owner

    template:
      data:
        DATABASE_URL: >-
          postgres://{{ .username }}:{{ .password }}@postgres-postgresql.postgres.svc.cluster.local:5432/demodb?sslmode=disable

  dataFrom:
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: VaultDynamicSecret
          name: postgres-demo-creds
