apiVersion: generators.external-secrets.io/v1alpha1
kind: VaultDynamicSecret
metadata:
  name: postgres-demo-creds
  namespace: demo
spec:
  path: /database/creds/miniflux
  method: GET
  resultType: Data

  provider:
    server: "http://openbao.openbao.svc:8200"

    auth:
      kubernetes:
        mountPath: kubernetes
        role: eso-demo

        serviceAccountRef:
          name: demo
